from __future__ import annotations

CONFIRM_CB_PREFIX = "confirm:"
CANCEL_CB_PREFIX = "cancel:"

CONFIRM_TOKEN_RETAIN_TTL_SEC_DEFAULT = 60

BASELINE_MIGRATION_MIN_COUNT = 1
BASELINE_MIGRATION_MAX_COUNT = 1
